name: amy

dependencies:
  - base
  - bytestring
  - containers
  - llvm-hs
  # - llvm-hs-pretty
  - llvm-hs-pure
  - megaparsec
  - mtl
  - parser-combinators
  - prettyprinter
  - scientific
  - text
  - validation

ghc-options: -Wall

library:
  source-dirs: library

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - amy
      - hspec
      - hspec-discover
      - hspec-megaparsec
      - shakespeare

executables:
  amy:
    source-dirs: executables
    main: Main.hs
    dependencies:
      - amy
      - haskeline
